[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ['ffconnect*']

[tool.setuptools.package-data]
'ffconnect.simulator' = ["*", "**/*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project]
name = "ffconnect"
version = "0.1.0"
authors = [
  { name="Zekai Chen", email="zkaichen@student.ubc.ca" },
]
dynamic = ["dependencies"]
description = "Step-locked closed-loop Python interface for FAST.Farm wind farm simulations, designed for reinforcement learning policy training"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
]

[project.urls]
Homepage = "https://github.com/DavidChen0429/FF_Python_Toolbox"
Issues = "https://github.com/DavidChen0429/FF_Python_Toolbox/issues"
